blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.home_view, name='home'),  
    path('p/<slug:slug>/',views.post_detail_view,name='post-detail'),  
    path('post/new/',views.post_create_view,name='post-create'),
    path('post/<int:pk>/update/', views.post_update_view, name='post-update'),  
    path('post/<int:pk>/delete/',views.post_delete_view, name='post-delete'), 
    path('search/nccbuddies/', views.search_view, name='search'), 
    path('like/post',views.like_view,name='like'),
    path('report/post/',views.post_report_view,name='report'),
    path('report/user/',views.user_report_view,name='report-user'),
    path('<str:username>/notifications/',views.notifications_view,name='notifications'),
    path('<str:username>/notifications/update/',views.notifications_update_view,name='notifications-update'),
    path('<str:username>/notifications/count/',views.notifications_unread_count_view,name='notifications-count'),
]

blog_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

admin.site.site_header = settings.ADMIN_SITE_HEADER


urlpatterns = [
    path('admin/site/', admin.site.urls), 
    path('', include('blog.urls', namespace='blog')), 
    path('account/register/', user_views.register, name='register'),
    path('account/profile-update/',user_views.updateProfile,name='profile-update'),
    path('account/follow-unfollow/<int:pk>/',user_views.userFollowUnfollow,name="follow-unfollow"),
    path('account/password-change/', user_views.change_password, name='change-password'),

    path('account/login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'), 
    path('account/logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),  
    path('account/password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),  
    path('account/password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),  
    path('account/password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),  
    path('account/password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),  
    path('account/community/', include('footer.urls', namespace='community')),
    path('<str:username>/', user_views.profile, name='profile'),
    path('validate/username/', user_views.validate_username,name='validate-username'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'footer.views.error_404_view'

footer/urls.py
from django.urls import path
from . import views

app_name = "community"

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('contribute/', views.contribute, name='contribute'),
    path('sponsor/', views.sponsor, name='sponsor'),
    path('guidelines/', views.guidelines, name='guidelines'),  
    path('about/', views.about, name='about'),  
    path('facts/',views.facts,name='facts')

]

users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


from PIL import Image
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill,Transpose
from taggit.managers import TaggableManager


WING = [
    
    ('ARMY','ARMY'),
    ('NAVAL','NAVAL'),
    ('AIR FORCE','AIR FORCE')
    
]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=25,blank=True)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    image_thumbnail_user = ImageSpecField(source='image',
                                      processors=[Transpose(),ResizeToFill(170, 170)],
                                      format='JPEG',
                                      options={'quality': 100})

    description = models.CharField(max_length=100, blank=True)
    follows = models.ManyToManyField(User,related_name="follows",blank=True)
    followers = models.ManyToManyField(User,related_name="followers",blank=True)
    camps = TaggableManager(blank=True)
    wing = models.CharField(max_length=10,choices=WING,blank=True)
    def __str__(self):
        return f"{self.user.username}'s Profile"



REASON = [
    
    ('SPAM','SPAM'),
    ('INAPPROPRIATE','INAPPROPRIATE'),
    
]


class UserReport(models.Model):
    reported_user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='reported_user')
    reason = models.CharField(max_length=10,choices=REASON)
    reporting_user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='reporting_user')
    date_reported = models.DateTimeField(default=timezone.now) 

    def __str__(self):
        return self.reported_user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

from .models import Profile, UserReport


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    camps = TaggableManager(verbose_name=u'Pasta')
    class Meta:
        model = Profile
        fields = ['image','name','description','wing','camps']


class ReportUserForm(forms.ModelForm):
    class Meta:
        model = UserReport
        fields = ['reason']

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm,ReportUserForm
from blog.models import Post, Notification
from django.contrib.auth.models import User
from django.http import JsonResponse


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created!\
                            You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    
    context = {'form': form}
    template_name = 'users/register.html'
    
    return render(request, template_name, context)

def validate_username(request):
    username = request.GET.get('username',None)
    data = {
        'is_taken':User.objects.filter(username__iexact=username).exists()
    }
    print(data)
    return JsonResponse(data)


# @login_required
def profile(request,username=None):
    report_form = ReportUserForm()
    user =  get_object_or_404(User,username=username)
    post_list = Post.objects.filter(author=user).order_by('-id')
    post_count = post_list.count()
    page = request.GET.get('page', 1)
    paginator = Paginator(post_list, 4)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)    
    
    context = {
        'report_form':report_form,
        'posts':posts,
        'user_id':user,
        'post_count':post_count,
    }
    template_name = 'users/profile.html'

    return render(request, template_name, context)

@login_required
def updateProfile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile',username=request.user.username)
        else:
            messages.error(request, f'Username already exists or in use!')
            return redirect('profile-update')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        context = {
            'u_form': u_form,
            'p_form': p_form,
        }
        template_name = 'users/update_profile.html'

        return render(request, template_name, context)


@login_required
def userFollowUnfollow(request,pk=None):
    current_user = request.user
    other_user = User.objects.get(pk=pk)

    if other_user not in current_user.profile.follows.all():
        current_user.profile.follows.add(other_user)
        other_user.profile.followers.add(current_user)
        
        notify = Notification.objects.create(sender=current_user,receiver=other_user,action="started following you.")

    else:
        current_user.profile.follows.remove(other_user)
        other_user.profile.followers.remove(current_user)
    return redirect('profile',username=other_user.username)


@login_required
def  change_password(request):
    if request.method == 'POST':
        form  =  PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('profile',username=request.user.username)
        else:
            return redirect('change-password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form':form}
        return render(request, 'users/change_password.html',args)

users/templates/users/change_password.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %} 
{% block title %}<title> @{{request.user.username}} change password </title>{% endblock %}

{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Change Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info btn-sm" type="submit">Change</button>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/login.html
{% extends "blog/base.html" %} 
{% load crispy_forms_tags %}
{% block title %}
  <title>Login </title>
{% endblock %} 
{% block content %}
<div>
    <small class="text-muted">
        <b>Need An Account?</b> 
        <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
    </small>
</div>
<br>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info btn-sm" type="submit">Login</button>
            <small class="text-muted ml-2">
                <a href="{% url 'password_reset' %}">Forgot Password?</a>
            </small>
        </div>
    </form>
    <div class="border-top pt-3">
        
    </div>
</div>
<div class="card">
    <div class="card-body">
            <li>Don't have an account yet? <a href="{% url 'register' %}"> Click here</a> to register.</li>
        </ul>
    </div>
</div><br>
{% endblock content %}

users/templates/users/logout.html
 {% extends "blog/base.html" %}
 {% block title %}
  <title>logged out </title>
{% endblock %} 
 {% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3 pb-3">
    <small class="text-muted">
        <a href="{% url 'login' %}">Log In Again</a>
    </small>
</div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "blog/base.html" %} \

{% load crispy_forms_tags %} 

{% block title %}
  <title>Password Reset </title>
{% endblock %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info btn-sm"
                    type="submit">Request Password Reset</button>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "blog/base.html" %} 
{% load crispy_forms_tags %}
{% block title %}<title> @{{request.user.username}} - </title>{% endblock %}
{% block content %}

<style type="text/css">
.col-lg-8 p {
    margin-top: 0;
    margin-bottom: 0;
}
</style>

<div class="content-section-orange">
    <div class="media">
        <div class="profile-image-div">
            <img class="rounded-circle account-img" id="profileImage" src="{{ user_id.profile.image_thumbnail_user.url }}">
            {% if user_id == request.user %}
            <a href="{% url 'profile-update' %}" data-toggle="tooltip-update" title="Edit Profile">
                
            </a>
            {% endif %}
        </div>
        
        <div class="media-body-profile">
            <div class="user-info">
            	{% if user_id.profile.name %}
                	<h2 class="account-heading">{{ user_id.profile.name }}</h2>
                	<p class="text-secondary username-p">
	                <span id="username">
	                	{{ user_id.username }}
	                </span>
	                <span id="report-dots-span">
		                {% if not user_id == request.user %}
		                	{% if user.is_authenticated %}
		                    <a data-target="#ReportModalCenter" data-toggle="modal" class="report-dots">
					            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
					            width="24" height="24"
					            viewBox="0 0 172 172"
					            style=" fill:#000000;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#cccccc"><path d="M43,71.66667c-7.91608,0 -14.33333,6.41725 -14.33333,14.33333c0,7.91608 6.41725,14.33333 14.33333,14.33333c7.91608,0 14.33333,-6.41725 14.33333,-14.33333c0,-7.91608 -6.41725,-14.33333 -14.33333,-14.33333zM86,71.66667c-7.91608,0 -14.33333,6.41725 -14.33333,14.33333c0,7.91608 6.41725,14.33333 14.33333,14.33333c7.91608,0 14.33333,-6.41725 14.33333,-14.33333c0,-7.91608 -6.41725,-14.33333 -14.33333,-14.33333zM129,71.66667c-7.91608,0 -14.33333,6.41725 -14.33333,14.33333c0,7.91608 6.41725,14.33333 14.33333,14.33333c7.91608,0 14.33333,-6.41725 14.33333,-14.33333c0,-7.91608 -6.41725,-14.33333 -14.33333,-14.33333z"></path></g></g></svg>
					        </a>
					        {% endif %}
					    {% else %}
		                {% endif %}                	
	                </span>
                </p>
                {% else %}
                	<h2 class="account-heading">{{ user_id.username }}
                		<span id="report-dots-span">
		                {% if not user_id == request.user %}
		                    <a data-target="#ReportModalCenter" data-toggle="modal" class="report-dots">
					            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
					            width="24" height="24"
					            viewBox="0 0 172 172"
					            style=" fill:#000000;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#cccccc"><path d="M43,71.66667c-7.91608,0 -14.33333,6.41725 -14.33333,14.33333c0,7.91608 6.41725,14.33333 14.33333,14.33333c7.91608,0 14.33333,-6.41725 14.33333,-14.33333c0,-7.91608 -6.41725,-14.33333 -14.33333,-14.33333zM86,71.66667c-7.91608,0 -14.33333,6.41725 -14.33333,14.33333c0,7.91608 6.41725,14.33333 14.33333,14.33333c7.91608,0 14.33333,-6.41725 14.33333,-14.33333c0,-7.91608 -6.41725,-14.33333 -14.33333,-14.33333zM129,71.66667c-7.91608,0 -14.33333,6.41725 -14.33333,14.33333c0,7.91608 6.41725,14.33333 14.33333,14.33333c7.91608,0 14.33333,-6.41725 14.33333,-14.33333c0,-7.91608 -6.41725,-14.33333 -14.33333,-14.33333z"></path></g></g></svg>
					        </a>
					    {% else %}
			                    
		                {% endif %}                	
	                </span>
                	</h2>
                {% endif %}


            </div>
            <div class="user-follow-status">
                
                {% if user_id == request.user %}
					<a href="{% url 'blog:post-create' %}" data-toggle="tooltip" title="Add Post">
                		<button type="button" class="btn btn-primary btn-sm">Add Post</button>
                	</a>
                {% else %}
                <a href="{% url 'follow-unfollow' user_id.id %}">
                		{% if user_id in request.user.profile.follows.all %}
                		<button type="button" class="btn btn-outline-secondary btn-sm">Unfollow</button>
                		{% else %}
                		<button type="button" class="btn btn-info btn-sm">Follow</button>
                		{% endif %}
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="user-network">
        <div class="followers">
            <span><b>{{user_id.profile.followers.count}}</b></span>
            <a class="link-style-none" href="#" data-toggle="modal" data-target="#2"><span>followers</span></a>
        </div>
        <div class="following">
            <span><b>{{user_id.profile.follows.count}}</b></span>
            <a class="link-style-none" href="#" data-toggle="modal" data-target="#3"><span>following</span></a>
        </div>
        <div class="followers">
            <span><b>{{post_count}}</b></span>
            <span>posts</span>
        </div>
    </div>


</div>

{% if user_id.profile.description or user_id.profile.camps.count != 0 %}
<div class="content-section-blue">
    <p>
     	{% for camp in user_id.profile.camps.all %}
    	<span class="badge badge-dark">{{ camp.name }}</span>
    	{% endfor %}
    </p>
    {{user_id.profile.description}}
</div>
{% endif %}

	<div class="infinite-container">
    {% for post in posts %}
		<article class="media content-section infinite-item">
	        <div class="media-body">
	            <div class="article-metadata">
	                <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}
	                </small>
	            </div>
	            <div class="img-heading-wrap">
	              <div class="article-post-img">
	                <img class="post-img" src="{{post.image_thumbnail.url}}">
	              </div>
	              <p class="h-font">
	                <a class="article-title"
	                     href="{% url 'blog:post-detail' post.slug %}">{{ post.title }}
	                  </a>
	              </p>              
	            </div>
	            <a class="read-more" href="{% url 'blog:post-detail' post.slug %}"><small>Read More</small></a>
	            <div class="post-applause">
	              <span class="badge badge-secondary">{{post.likes.count}} NCC Claps</span>
	            </div>
	        </div>
	    </article>
	{% empty %}
		{% if user_id == request.user %}
			<p>To add post click Add Post button.</p>
			<p>To add or edit more information on your profile click on pencil icon.</p>
			<br>
		{% endif %}
    {% endfor %}
    </div>
    <div class="loading" style="display: none;">
      Loading...
    </div>
    {% if posts.has_next %}
      <a class="infinite-more-link" style="display: none;" href="?page={{ posts.next_page_number }}">More</a>
    {% endif %}




{% if user.is_authenticated %}

<div class="modal fade bd-example-modal-lg modal-padding" id="2" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
        <div class="modal-body">
        	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          		<span aria-hidden="true">&times;</span>
    		</button>
        	<p>followers</p>

        	{% for pro in user_id.profile.followers.all %}
        	<div class="user-follow-status-model">
        		<div class="user-follow-status-model-image">
        			<img class="rounded-circle account-img-f" src="{{pro.profile.image_thumbnail_user.url}}">
        		</div>
        		<div class="user-follow-status-model-name">
        			<a href="{% url 'profile' pro.username %}" class="link-style-none">{{pro.username}}</a>
        		</div>
        		
        	</div>
        	
        	
            {% empty %}
            <div class="user-follow-status-model">
        		<div class="user-follow-status-model-name">
        			<a href="#" class="link-style-none">0 followers</a>
        		</div>
        	</div>				
        	{% endfor %}
        </div>
      
    </div>
  </div>
</div>

<div class="modal fade bd-example-modal-lg modal-padding" id="3" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
    	<div class="modal-body">
    		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          		<span aria-hidden="true">&times;</span>
    		</button>
        	<p>following</p>

        	{% for pro in user_id.profile.follows.all %}
        	<div class="user-follow-status-model">
        		<div class="user-follow-status-model-image">
        			<img class="rounded-circle account-img-f" src="{{pro.profile.image_thumbnail_user.url}}">
        		</div>
        		<div class="user-follow-status-model-name">
        			<a href="{% url 'profile' pro.username %}" class="link-style-none">{{pro.username}}</a>
        		</div>
        	</div>
            {% empty %}
           <div class="user-follow-status-model">
        		<div class="user-follow-status-model-name">
        			<a href="#" class="link-style-none">0 following</a>
        		</div>
        	</div>			
        	{% endfor %}
        </div>
      
    </div>
  </div>
</div>

<!-- Report USerModal -->
<div class="modal fade" id="ReportModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Report User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'blog:report-user' %}" method="POST" id="report-form" name="{{user_id.id}}">
          {% csrf_token %}
          {{report_form | crispy}}
          <button type="submit" class="btn btn-outline-primary" style="float: right;">Report</button>
        </form>
        <p id="report-message" style="display: none;">Your response has been reported.</p>
      </div>
    </div>
  </div>
</div>
{% else %}
<div class="modal fade bd-example-modal-lg modal-padding" id="2" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
        <div class="modal-body">
        	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          		<span aria-hidden="true">&times;</span>
    		</button>
        	<p><a href="{% url 'login' %}">Login</a> to see the list.</p>
        	
        </div>
      
    </div>
  </div>
</div>
<div class="modal fade bd-example-modal-lg modal-padding" id="3" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
    	<div class="modal-body">
    		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          		<span aria-hidden="true">&times;</span>
    		</button>
        	<p><a href="{% url 'login' %}">Login</a> to see the list.</p>
        	
        </div>
      
    </div>
  </div>
</div>
{% endif %}
{% endblock content %}

{% block script %}
{% if user.is_authenticated %}

<script type="text/javascript">
$(document).ready(function () {

$('#report-form').on('submit',function(event){

    event.preventDefault();
    $.ajax({
      url: "{% url 'blog:report-user' %}",
      type: "POST",
      data: {'reason':$('#id_reason').val(),'pk': $(this).attr('name'),'csrfmiddlewaretoken': '{{ csrf_token }}'},
      success: function(response) {
            
              $('#report-form').hide();
              $('#report-message').show();

          },
      error: function(rs, e) {
            $('#report-form').hide();
            $('#report-message').show();
          },
    })
    
});


});
  
</script>
<script type="text/javascript">
	$(document).ready(function(){
	  $('[data-toggle="tooltip"]').tooltip();

	});
</script>
{% endif %}

<script>
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        onBeforePageLoad: function () {
        	$('.loading').show();
    	},
        onAfterPageLoad: function ($items) {
            $('.loading').hide();
        }
    });
</script>
{% endblock %}

users/templates/users/register.html
 {% extends "blog/base.html" %} 
 {% load crispy_forms_tags %} 
 {% block title %}
  <title>Sign Up </title>
{% endblock %}
 {% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Your Account</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <small>By signing up you are agree to follow nccbuddies guidelines (<a href="{% url 'community:guidelines' %}">click here</a> to read)</small>.<br><br>
            <button class="btn btn-outline-info btn-sm" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
                <b>Already Have An Account? </b>
                <a class="ml-2" href="{% url 'login' %}">Log In</a>
        </small>
    </div>
</div>
{% endblock content %}


{% block script %}

<script type="text/javascript">
    
    $("#id_username").change(function(){

        var username = $(this).val();

        $.ajax({

            url:'{% url "validate-username" %}',
            data: {
                'username':username
            },
            dataType: 'json',
            success: function(data){
                if (data.is_taken) {
                    alert("Username Already Taken!");
                }
            }

        })

    });

</script>


{% endblock %}

users/templates/users/update_profile.html
{% extends "blog/base.html" %} 
{% load static %}
{% load crispy_forms_tags %} 

{% block title %}<title> @{{request.user.username}} profile update </title>{% endblock %}

{% block content %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data" id="user-update-form">
        {% csrf_token %}
        <fieldset class="form-group">
            <div class="profile_update border-bottom">
                <legend class="mb-3">Update Profile
                </legend>
            </div>
            {{ u_form|crispy }} 
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-info btn-sm" type="submit" id="submit-update-btn">Update</button>
        </div>
    </form>
    <a class="nav-item nav-link" style="position: absolute;right: 25px;bottom: 25px;font-size: 15px;" href="{% url 'logout' %}">Logout</a>
    <div class="border-top pt-3">
        <small class="text-muted">
            <b>Change Password?</b>
            <a class="ml-2" href="{% url 'change-password' %}">click here</a>
        </small>
    </div>
</div>
<div id="loader">
    <p style="position: absolute;top: 50%;right: 50%;color: white">Updating...</p>
</div>
{% endblock content %}

{% block script %}

<script type="text/javascript">
    $(document).ready(function(){
        // $('#div_id_image').children('div').addClass('currentPhoto');
        // $('.currentPhoto').children('a').hide();
        // let isTextNode = (_, el) => el.nodeType === Node.TEXT_NODE;
        // $('.currentPhoto').contents().filter(isTextNode).remove();
        // var img = document.createElement("IMG");
        // img.src = '{{ user.profile.image_thumbnail_user.url }}';
        // img.setAttribute('class', 'account-img');
        // $('.currentPhoto').prepend('<br>Change Image'); 
        // $('.currentPhoto').prepend(img);
        $('#hint_id_camps').html('Add comma between Camps you have attended!');
        $('#div_id_camps label').html('Camps*');

        $('#submit-update-btn').on('click',function(e){
            if ($('#id_username').val()!=="" && $('#id_email').val()!==""){
                $('#loader').show()
            }
            else{
                $('#loader').hide()

            }
        })

    });
</script>
{% endblock %}